version: '3.7'

services:
  postgresdb:
    container_name: postgres-core
    image: postgres
    restart: on-failure
#    restart: always
    env_file:
      - ./env/db.env
    ports:
      - "1436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  fastapicore:
    container_name: fastapi-core
    build:
      context: .
    env_file:
      - ./env/fastapi.env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8001:5000"
    restart: always
    depends_on:
      - postgresdb
      - pgadmin
#    command: ./start-reload.sh
    # tty: true
  pgadmin:
    container_name: pgadmin-core
    image: dpage/pgadmin4
    env_file:
      - ./env/pgadmin.env
    ports:
      - "5050:80"
    depends_on:
      - postgresdb
    restart: always





volumes:
  pgdata:
    external: true
